### ISSUE TITLE
Run sync_with_poetry after changing the .pre-commit.config.yaml

### ISSUE THREAD

**Issue by davidsampimon** [floatingpurr/sync_with_poetry#12]
I noticed that sync_with_poetry only runs after changing and committing the poetry.lock file. Since in our project there are more frequent changes within .pre-commit.config.yaml, it would be great that a commit of this file would also trigger "sync_with_poetry". Is this possible?

**Comment by floatingpurr** [comment]
Hi again @davidsampimon! The rational behind this mechanism is pulling versions of python packages from `poetry.lock`, and then updating corresponding python-based hooks in `.pre-commit.config.yaml` (but not backward!). That's the reason why this hook is tightly coupled with `poetry.lock`.

Can you provide more details about your use case?

PS: pre-commit lets users run this hook manually, if necessary.

**Comment by davidsampimon** [comment]
Sure, we use poetry for all our projects and our CI/CD pipeline requires that all projects have certain linters/formatters as dev dependencies (black, flake8 etc.). So every project starts out with a poetry.lock file with those dev dependencies already included. 

Since using pre-commit is not required on our projects, it is quite common that this is set up in a later stage. What then often happens is that the individual devs do not pay attention to the linters/formatters already present in the poetry.lock file and use a different version in their .pre-commit.config.yaml file. 

I was hoping that with 'sync_with_poetry' we could check the rev tags each time there is a change in either .pre-commit-config.yaml or the poetry.lock file to make sure the poetry.lock file is respected

**Comment by davidsampimon** [comment]
Thanks for your response @floatingpurr , it is clear now!

**Comment by real-yfprojects** [comment]
Ok, so why isn't *sync_with_poetry* run on changes of `.pre-commit-config.yaml`? I would expect it to enforce the rev defined in the `poetry.lock`, so that the revs aren't changed for example when (accidentally) running `pre-commit autoupdate`.

**Comment by floatingpurr** [comment]
Hi @real-yfprojects, swp works the other way around. You use poetry to manage your dependencies, and swp synchronizes the pre-commit packages accordingly. The reverse way is not supported.

**Comment by real-yfprojects** [comment]
> Hi @real-yfprojects, swp works the other way around. You use poetry to manage your dependencies, and swp synchronizes the pre-commit packages accordingly. The reverse way is not supported.

I know that and I am not requesting that at all. I also know that I already expressed clearly what I am asking for. Please read my comment again. If you still don't understand, I will try explaining it differently.

**Comment by floatingpurr** [comment]
Hello again. To be honest, I do not understand the reason why swp should be involved in your use case. Why should you run swp upon changes on `.pre-commit-config.yaml`? This looks like an anti-pattern, given the rationale of this package. 

Even if you accidentally run pre-commit autoupdate, there are many ways to revert back the modifications (e.g., undoing local changes with git or manually running swp again to fix just the versions of packages controlled by swp). Moreover, all the hooks are run before each commit, so swp will sync versions anyway.

**Comment by floatingpurr** [comment]
I see, but I'm still not convinced that running swp upon each modification on `.pre-commit-config.yaml` by default can be a good pattern for general usage. In addition, the [config option](https://github.com/floatingpurr/sync_with_poetry#args) should be modified accordingly. 

Can overriding the [`file`](https://pre-commit.com/#pre-commit-configyaml---hooks) pattern in your very specific hook mapping be an option to tackle your problem?

**Comment by real-yfprojects** [comment]
> Can overriding the [`file`](https://pre-commit.com/#pre-commit-configyaml---hooks) pattern in your very specific hook mapping be an option to tackle your problem?

Already did that, but I thought that it would be a sensible default.
