### ISSUE TITLE
Allow passing in custom db

### ISSUE THREAD

**Issue by joshuata** [floatingpurr/sync_with_poetry#17]
It would be very useful to be able to define a file with mappings that could be passed as an argument/config option to the hook so that a user could define their own outside of those shipped with the hook

**Comment by floatingpurr** [comment]
Hi @joshuata, thanks for this suggestion. You can now use `--db` to pass your custom mapping as a json file.

See https://github.com/floatingpurr/sync_with_poetry/releases/tag/0.4.0 for more
