### ISSUE TITLE
FR: Strip `frozen: x.x.x` comments

### ISSUE THREAD

**Issue by real-yfprojects** [floatingpurr/sync_with_poetry#24]
I like to regularly update my pre-commit hooks with `pre-commit autoupdate --freeze`. Afterwards I run SWP to pin those hooks that are also configured via poetry. (Some hooks aren't python packages so I can't manage all of them via poetry)

This result in lines like the following

```yaml
rev: 1.7.5 # frozen: 1.7.5
```

```yaml
rev: 22.10 # frozen: 22.12
```

I like that SWP preserves comments (in contrast to `pre-commit autoupdate`). But I would like it to remove `frozen: xxx` comments still.

**Comment by floatingpurr** [comment]
I see. I think that this feature should be disabled by default and enabled with an arg. I'm not sure to be able to focus on that shortly. What about using another comment clearing hook to process this and other comment types?

**Comment by real-yfprojects** [comment]
> I'm not sure to be able to focus on that shortly.

I can write a PR.

> What about using another comment clearing hook to process this and other comment types?

You mean writing a pre-commit hook from scratch that determines whether a *rev* is frozen or not and strips the comment depending on that? That would be a nice tool but I think this features makes sense for SWP too.

**Comment by floatingpurr** [comment]
> I can write a PR.

Yes, great! I've not analyzed the scenario, but I guess that you should use a regex to match **only** the comments automatically added by pre-commit autoupdate (i.e., `# frozen: <package_version>` where `<package_version>` can be written in many forms, add some unit tests, and update the documentation. Don't forget to make this feature turned off by default.

> You mean writing a pre-commit hook from scratch that determines whether a rev is frozen or not and strips the comment depending on that? That would be a nice tool but I think this features makes sense for SWP too.

IMHO, yes and no. It could be baked into SWP, but I wonder that there could be many cases in which you might want to strip this, or other comment types according to your local needs. Using a dedicated hook responsible for doing this things looks to me a more natural and general approach. And it can be used independently of SWP.

**Comment by floatingpurr** [comment]
I'll close it for now. Feel absolutely free to reopen this issue as soon as there is more to discuss about it.

**Comment by real-yfprojects** [comment]
I have written a pre-commit hook that - among other things - solves this issue.
You can find more about it in its [repo](https://github.com/real-yfprojects/check-pre-commit-config). I am very glad I found the python library [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) that allows parsing and dumping yaml without altering the formatting of the  file. This saved me from a lot of work since I didn't need to use regex based substitution for implementing the code style fixes.
