### ISSUE TITLE
Autoupdate for flake8 does not work

### ISSUE THREAD

**Issue by chris-rl** [floatingpurr/sync_with_poetry#5]
Hi,
I tried this pre-commit-hook. It seems like something is not working properly (at least for me).

I have the following setup:

_.pre-commit-config.yaml_
```
- repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'pycodestyle==2.7.0',  # E,W
            'pyflakes==2.3.0',  # F
            'mccabe==0.6.1',  # C
            'flake8-bugbear==21.3.2',  # B
            'flake8-builtins==1.5.3',  # A
            'flake8-comprehensions==3.3.1',  # C4
            'flake8-debugger==4.0.0',  # T1
            'flake8-logging-format==0.6.0',  # G
            'flake8-print==4.0.0',  # T0
        ]
        args: [
            '--select=E,W,F,C,B,A,C4,T1,G,T0',
            '--ignore=W503,B305,A003,G003,G004',
            '--max-complexity=10',
            '--max-line-length=120',
        ]
- repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.2.0
    hooks:
      - id: sync_with_poetry
        name: sync pre-commit dependencies with poetry
        args: [
            '--config', 'src/python/.pre-commit-config.yaml',
            '--all',  # Scan all dependencies in poetry.lock (main and dev)
        ]
```

_poetry.lock_
```
[[package]]
name = "flake8"
version = "4.0.1"
description = "the modular source code checker: pep8 pyflakes and co"
category = "dev"
optional = false
python-versions = ">=3.6"

[package.dependencies]
mccabe = ">=0.6.0,<0.7.0"
pycodestyle = ">=2.8.0,<2.9.0"
pyflakes = ">=2.4.0,<2.5.0"
```

When running the pre-commit hook, _flake8_ won't update. Other dependencies like _black **do update**_.
First I thought it might be because of a major version jump. But the issue also remains if the rev in pre-commit-config is `4.0.0`. It won't update to `4.0.1` (from _poetry.lock_).

Any ideas?

**Comment by floatingpurr** [comment]
Hi. The problem lies in the repo url of flake8. Indeed, https://gitlab.com/pycqa/flake8 says:

>This is a mirror of github.com/pycqa/flake8

In `db.py`, we have only the main repo
https://github.com/floatingpurr/sync_with_poetry/blob/d7456aaa0f70302d9ef76430c35f545227b2a322/sync_with_poetry/db.py#L10-L12

That's the reason why there's no match with https://gitlab.com/pycqa/flake8 (and any updates by this hook!).

**Comment by chris-rl** [comment]
Hi!
Thank you for the fast investigation!
Ah, in fact, I oversaw this tiny difference in the repo URL git**la**b / git**hu**b.
I updated my own _.pre-commit-config.yaml_

Anyways, I think it would be good to add an entry to the `db.py` for this mirrow.

**Comment by floatingpurr** [comment]
Hi @chris-rl! You are welcome. Currently, I prefer to limit entries in `db.py` sticking with the [hooks officially supported by .pre-commit](https://pre-commit.com/hooks.html).
